// Compatibility exports. New code imports APIs from its feature module.
export { authExpiredEvent } from '@/api/client'
export {
  fetchAvailabilityProviders,
  checkProviderAvailability,
  fetchConfig,
  updateConfig,
  fetchTools,
  downloadFFmpeg,
} from '@/features/settings/api'
export {
  fetchAuthStatus,
  loginWithPassword,
  logoutSession,
  changePassword,
  fetchExtensionTokens,
  createExtensionToken,
  rotateExtensionToken,
  deleteExtensionToken,
} from '@/features/auth/api'
export {
  fetchVideos,
  openVideoFile,
  playVideoFile,
  playVideoPlaylist,
  revealVideoLocation,
  incrementVideoPlayCount,
  fetchPlaybackInfo,
  fetchVideoScreenshots,
  fetchVideoScreenshotsByIds,
  createVideoScreenshot,
  deleteVideoScreenshot,
  updateVideoCover,
  resetVideoCover,
  renameVideoLocation,
  deleteVideoLocation,
} from '@/features/video/api'
export {
  fetchTags,
  createTag,
  fetchTagCategories,
  createTagCategory,
  reorderTagCategories,
  renameTagCategory,
  deleteTagCategory,
  assignTagsCategory,
  deleteTag,
  deleteTagsBatch,
  renameTag,
  addTagToVideos,
  removeTagFromVideos,
  replaceTagsForVideos,
} from '@/features/tags/api'
export {
  updateVideoJavScrapeSettings,
  fetchVideoJavScrapePossibleCodes,
  manualVideoJavScrape,
  linkVideoToExistingJav,
  fetchJavItem,
  fetchJavs,
  fetchJavFilterOptions,
  getResolvedJavSampleImages,
  resolveJavSampleImages,
  fetchJavPrefixes,
  fetchJavTags,
  fetchJavTagCategories,
  updateJavCover,
  updateJavItem,
  createJavTag,
  createJavScrapedTag,
  organizeJavTags,
  createJavTagCategory,
  reorderJavTagCategories,
  renameJavTagCategory,
  deleteJavTagCategory,
  assignJavTagsCategory,
  renameJavTag,
  deleteJavTag,
  deleteJavTagsBatch,
  replaceJavTagsForItems,
  addJavTagToJavs,
  removeJavTagFromJavs,
  fetchJavIdols,
  createJavIdol,
  fetchJavIdolOptions,
  mergeJavIdols,
  updateJavIdol,
  javIdolAvatarUrl,
  javIdolAvatarCandidateUrl,
  fetchJavIdolAvatarOptions,
  updateJavIdolAvatar,
  refreshJavIdolAvatar,
  fetchJavStudios,
  fetchJavStudioOptions,
  mergeJavStudios,
  updateJavStudio,
  fetchJavStudioJavDBURL,
  fetchJavStudioPreview,
  fetchJavSeries,
  fetchJavSeriesJavDBURL,
  fetchJavSeriesPreview,
  fetchJavIdolPreview,
  fetchJavIdolJavDBURL,
  fetchJavJavDBURL,
  resolveJavIdols,
} from '@/features/jav/api'
export {
  fetchDirectories,
  createDirectory,
  browseDirectories,
  updateDirectory,
  deleteDirectory,
  processDirectory,
  scanDirectory,
} from '@/features/directories/api'
export {
  fetchDownloaderSettings,
  updateDownloaderSettings,
  updateCloudDrive2Settings,
  fetchCloudDrive2Token,
  testCloudDrive2,
  fetchDownloadJobs,
  createDownloadJob,
  retryDownloadJob,
  cancelDownloadJob,
  revealDownloadLocation,
  deleteDownloadJob,
} from '@/features/downloads/api'
export {
  fetchJavFavoriteGroups,
  createJavFavoriteGroup,
  renameJavFavoriteGroup,
  deleteJavFavoriteGroup,
  reorderJavFavoriteGroups,
  fetchJavFavoriteGroupItems,
  reorderJavFavoriteGroupItems,
  removeJavFavoriteGroupItems,
  fetchJavFavoriteSelection,
  replaceJavFavoriteGroups,
  addJavsToFavoriteGroups,
} from '@/features/favorites/api'
